#!/bin/sh /etc/rc.common

USE_PROCD=1
START=99
STOP=01
CONFIGURATION="grapheqd"

start_service () {
  config_load "${CONFIGURATION}"

  local address
  local port
  local raddress
  local rport
  local soundcard
  local user
  local args

  config_get address   @grapheqd[0] address
  config_get port      @grapheqd[0] port
  config_get raddress  @grapheqd[0] raddress
  config_get rport     @grapheqd[0] rport
  config_get soundcard @grapheqd[0] soundcard
  config_get user      @grapheqd[0] user

  args="-d"

  [ -n "$address" ]   && $args="$args -a '$address'"
  [ -n "$port" ]      && $args="$args -l '$port'"
  [ -n "$raddress" ]  && $args="$args -c '$raddress'"
  [ -n "$rport" ]     && $args="$args -r '$rport'"
  [ -n "$soundcard" ] && $args="$args -s '$soundcard'"
  [ -n "$user" ]      && $args="$args -u '$user'"

  procd_open_instance
  procd_set_param command /usr/sbin/grapheqd $args
  procd_set_param file /etc/config/grapheqd
  procd_set_param stdout  1
  procd_set_param stderr  1
  procd_close_instance
}
