#!/bin/sh /etc/rc.common

USE_PROCD=1
START=99
STOP=01
CONFIGURATION="grapheqd"

start_service () {
  config_load "${CONFIGURATION}"

  local address
  local port
  local raddress
  local rport
  local soundcard
  local username

  config_get address   grapheqd address
  config_get port      grapheqd port
  config_get raddress  grapheqd raddress
  config_get rport     grapheqd rport
  config_get soundcard grapheqd soundcard
  config_get username  grapheqd username

  [ -z "$username" ] && username="nobody"

  procd_open_instance
  procd_set_param command /usr/sbin/grapheqd -d
  procd_append_param command -u "$username"

  [ -n "$address" ]   && procd_append_param command -a "$address"
  [ -n "$port" ]      && procd_append_param command -l "$port"
  [ -n "$raddress" ]  && procd_append_param command -c "$raddress"
  [ -n "$rport" ]     && procd_append_param command -r "$rport"
  [ -n "$soundcard" ] && procd_append_param command -s "$soundcard"

  procd_set_param file /etc/config/grapheqd
  procd_set_param stdout  1
  procd_set_param stderr  1
  procd_close_instance
}
